2021-04-18 23:10:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:10:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:10:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:13:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:13:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:13:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:16:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:16:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:16:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USER" not found; SQL statement:
SELECT "USER".ID, "USER"."NAME", "USER".NICKNAME, "USER".PASSWORD, "USER".ROLE_ID FROM "USER" [42102-199]
2021-04-18 23:26:53 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/mnt/data/workspace/idea/my_blog/myh2file.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:/mnt/data/workspace/idea/my_blog/myh2file.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/mnt/data/workspace/idea/my_blog/myh2file.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
